### ISSUE TITLE
dont work normalize slashes

### ISSUE THREAD

**Issue by kygn1998** [atom-community/autocomplete-paths#129]
![Imgur](http://i.imgur.com/yXQcYgt.png)
![Imgur](http://i.imgur.com/RVFkR95.png)

I'm using 
atom 1.19.0
autocomplete-paths 2.5.0 
windows 10 home x64

In what environment does it work?

**Comment by kygn1998** [comment]
Yesterday, after being newly installed, it has not been converted. (sorry i'm using translator)

**Comment by linjialiang** [comment]
I have also encountered this problem, which has not been solved until now

**Comment by linjialiang** [comment]
Now I choose to disable it!

**Comment by saschagehlich** [comment]
I'll work on this later today. Windows support was not high priority for me yet.

**Comment by saschagehlich** [comment]
@linjialiang @kygn1998 Fixed in 2.6.0

**Comment by linjialiang** [comment]
@saschagehlich Sorry, I have updated 2.6.0, but it still can't be used.
I tried to change the version to 1.6.0, but I couldn't use it.
This is the only problem that I have since I upgraded atom to 1.19.0, and my current version is 1.19.1.

**Comment by kygn1998** [comment]
2.8.0 is working XD thx
